CREATE TABLE measurements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_id VARCHAR(100) NOT NULL,
    customer_id BIGINT NOT NULL,
    order_id BIGINT,
    version INT NOT NULL,
    is_latest BOOLEAN NOT NULL DEFAULT TRUE,
    chest DOUBLE,
    waist DOUBLE,
    hip DOUBLE,
    shoulder DOUBLE,
    sleeve DOUBLE,
    inseam DOUBLE,
    outseam DOUBLE,
    neck DOUBLE,
    height DOUBLE,
    weight DOUBLE,
    fit_preference VARCHAR(100),
    note TEXT,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_measure_customer FOREIGN KEY (customer_id) REFERENCES users(id),
    CONSTRAINT fk_measure_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_measure_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_measure_group_latest (group_id, is_latest),
    INDEX idx_measure_customer (customer_id),
    INDEX idx_measure_order (order_id)
);

